services:
  - type: web
    name: seo-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: SCRAPINGDOG_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false